parameters:
  todo_api:
    port_http: 8080
    todo_api_image: "local/todo-api:latest"
secrets:
  todo_api:
    postgres_password: "admin"  
  postgres:
    postgres_password: "admin"
config:
  postgres:
    POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
    POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    POSTGRES_USER: "postgres"
  todo_api:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    POSTGRESDB_HOST: "postgres-service"
    POSTGRESDB_PORT: "5432"
    POSTGRESDB_USERNAME: "postgres"
    POSTGRESDB_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres-service:5432/postgresdb"
    POSTGRESDB_DATABASENAME: "postgresdb"
