---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "todo-api-config"
  labels:
    app.kubernetes.io/name: "apphost"
    app.kubernetes.io/component: "todo-api"
    app.kubernetes.io/instance: "{{.Release.Name}}"
data:
  ASPNETCORE_URLS: http://*:8080
  OTEL_SERVICE_NAME: "todo-api"  
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "{{ .Values.config.todo_api.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "{{ .Values.config.todo_api.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.todo_api.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.todo_api.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.config.todo_api.HTTP_PORTS }}"
  POSTGRESDB_HOST: "{{ .Values.config.todo_api.POSTGRESDB_HOST }}"
  POSTGRESDB_PORT: "{{ .Values.config.todo_api.POSTGRESDB_PORT }}"
  POSTGRESDB_USERNAME: "{{ .Values.config.todo_api.POSTGRESDB_USERNAME }}"
  POSTGRESDB_JDBCCONNECTIONSTRING: "{{ .Values.config.todo_api.POSTGRESDB_JDBCCONNECTIONSTRING }}"
  POSTGRESDB_DATABASENAME: "{{ .Values.config.todo_api.POSTGRESDB_DATABASENAME }}"
