---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "todo-api-deployment"
  labels:
    app.kubernetes.io/name: "apphost"
    app.kubernetes.io/component: "todo-api"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "apphost"
        app.kubernetes.io/component: "todo-api"
        app.kubernetes.io/instance: "{{.Release.Name}}"
    spec:
      containers:
        - image: "{{ .Values.parameters.todo_api.todo_api_image }}"
          livenessProbe:
            failureThreshold: 3
            successThreshold: 1
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            httpGet:
              path: "/alive"
              port: "http"
          name: "todo-api"
          envFrom:
            - configMapRef:
                name: "todo-api-config"
            - secretRef:
                name: "todo-api-secrets"
          ports:
            - name: "http"
              protocol: "TCP"
              containerPort: {{ .Values.parameters.todo_api.port_http }}
          imagePullPolicy: "IfNotPresent"
  selector:
    matchLabels:
      app.kubernetes.io/name: "apphost"
      app.kubernetes.io/component: "todo-api"
      app.kubernetes.io/instance: "{{.Release.Name}}"
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: "RollingUpdate"
