---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "todo-api-secrets"
  labels:
    app.kubernetes.io/name: "apphost"
    app.kubernetes.io/component: "todo-api"
    app.kubernetes.io/instance: "{{.Release.Name}}"
stringData:
  ConnectionStrings__postgresdb: "Host=postgres-service;Port=5432;Username=postgres;Password={{ .Values.secrets.todo_api.postgres_password }};Database=postgresdb"
  POSTGRESDB_PASSWORD: "{{ .Values.secrets.todo_api.postgres_password }}"
  POSTGRESDB_URI: "postgresql://postgres:{{ .Values.secrets.todo_api.postgres_password }}@postgres-service:5432/postgresdb"
type: "Opaque"
