---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "todo-api-service"
  labels:
    app.kubernetes.io/name: "apphost"
    app.kubernetes.io/component: "todo-api"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "apphost"
    app.kubernetes.io/component: "todo-api"
    app.kubernetes.io/instance: "{{.Release.Name}}"
  ports:
    - name: "http"
      protocol: "TCP"
      port: {{ .Values.parameters.todo_api.port_http }}
      targetPort: {{ .Values.parameters.todo_api.port_http }}

